x-gpu: &x-gpu
  deploy:
    resources:
      reservations:
        devices:
          - capabilities: [gpu]

services:
  dev:
    <<: *x-gpu
    image: ghcr.io/venetanji/audiocraft-server:main
    command: sleep infinity
    volumes:
      - ./server/:/app/server
      - huggingface:/root/.cache/huggingface
    profiles:
      - dev
    # useful to run the gradio demo
    ports:
      - 7860:7860
      - 8000:8000
  api:
    <<: *x-gpu
    image: ghcr.io/venetanji/audiocraft-server:main
    command: uvicorn server.main:app --host 0.0.0.0
    volumes:
      - ./server/:/app/server
      - huggingface:/root/.cache/huggingface
    ports:
      - 8000:8000

volumes:
  huggingface: