x-gpu: &x-gpu
  deploy:
    resources:
      reservations:
        devices:
          - capabilities: [gpu]

services:
  dev:
    <<: *x-gpu
    build: .
    command: sleep infinity
    volumes:
      - ./server/:/app/server
    ports:
      - 7860:7860